sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t mgadzala/docker-react .

script:
  - docker run mgadzala/docker-react yarn test --watchAll=false
